spring.application.name=inventory-service
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=St716944
spring.jpa.hibernate.ddl-auto=update